/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package equipo_trabajadorsalud;

import equipo0_dominio.TrabajadorSalud;

/**
 *
 * @author Alfonso Felix
 */
abstract class FmBase extends javax.swing.JFrame {

    private static TrabajadorSaludClient gateway;
    private static String token;
    private static TrabajadorSalud trabSalud;
    
    /**
     * Creates new form FmBase
     */
    public FmBase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public static TrabajadorSaludClient getGateway() {
        if(gateway==null){
            gateway=new TrabajadorSaludClient();
        }
        return gateway;
    }

    protected static void setToken(String token) {
        FmBase.token = token;
    }
    
    protected static String getToken() {
        return token;
    }
    
    protected static void setTrabSalud(TrabajadorSalud trabSalud){
        FmBase.trabSalud=trabSalud;
    }
    
    protected static TrabajadorSalud getTrabSalud(){
        return trabSalud;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
